version: '3.8'
services:
  webapp:
    image: webapp:latest
    build:
      context: .
      dockerfile: Dockerfile.multistage
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./src/config/environment.yaml:/app/src/config/environment.yaml:ro # Mount config as a volume
    environment:
      - APP_ENV=production

