version: "3.8"
services:
  webapp:
    image: webapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Ensure port mapping matches the exposed port
    restart: always
    environment:
      - APP_ENV=production
